//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Project/OpenELanguage/Compiler\openeParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="openeParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IopeneParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.opene_src"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpene_src([NotNull] openeParser.Opene_srcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.src_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_content([NotNull] openeParser.Src_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.program_set_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram_set_file([NotNull] openeParser.Program_set_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.data_structure_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_structure_file([NotNull] openeParser.Data_structure_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.global_variable_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_variable_file([NotNull] openeParser.Global_variable_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.dll_define_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDll_define_file([NotNull] openeParser.Dll_define_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.dll_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDll_command([NotNull] openeParser.Dll_commandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.global_variable_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_variable_list([NotNull] openeParser.Global_variable_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.global_variable_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_variable_item([NotNull] openeParser.Global_variable_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.edition_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdition_spec([NotNull] openeParser.Edition_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.struct_declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declare([NotNull] openeParser.Struct_declareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.table_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_comment([NotNull] openeParser.Table_commentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_list([NotNull] openeParser.Member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.member_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_item([NotNull] openeParser.Member_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.library_list_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_list_opt([NotNull] openeParser.Library_list_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.library_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_spec([NotNull] openeParser.Library_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.prog_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set([NotNull] openeParser.Prog_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.prog_set_variable_decl_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set_variable_decl_opt([NotNull] openeParser.Prog_set_variable_decl_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.prog_set_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set_variable_decl([NotNull] openeParser.Prog_set_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_decl([NotNull] openeParser.Variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.sub_program_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_program_opt([NotNull] openeParser.Sub_program_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.sub_program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_program([NotNull] openeParser.Sub_programContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.parameter_decl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_decl_list([NotNull] openeParser.Parameter_decl_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.parameter_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_decl([NotNull] openeParser.Parameter_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.local_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_decl([NotNull] openeParser.Local_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] openeParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConditionStatement</c>
	/// labeled alternative in <see cref="openeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionStatement([NotNull] openeParser.ConditionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStatement</c>
	/// labeled alternative in <see cref="openeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] openeParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="openeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] openeParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LoopStatement</c>
	/// labeled alternative in <see cref="openeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopStatement([NotNull] openeParser.LoopStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchStatement</c>
	/// labeled alternative in <see cref="openeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] openeParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] openeParser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="openeParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] openeParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RangeFor</c>
	/// labeled alternative in <see cref="openeParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeFor([NotNull] openeParser.RangeForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="openeParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] openeParser.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoWhile</c>
	/// labeled alternative in <see cref="openeParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhile([NotNull] openeParser.DoWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="openeParser.condition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] openeParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfTrueStmt</c>
	/// labeled alternative in <see cref="openeParser.condition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfTrueStmt([NotNull] openeParser.IfTrueStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.condition_statement_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_statement_else([NotNull] openeParser.Condition_statement_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.hierarchy_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierarchy_identifier([NotNull] openeParser.Hierarchy_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="openeParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] openeParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallWithArgu</c>
	/// labeled alternative in <see cref="openeParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallWithArgu([NotNull] openeParser.FuncCallWithArguContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallWithoutArgu</c>
	/// labeled alternative in <see cref="openeParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallWithoutArgu([NotNull] openeParser.FuncCallWithoutArguContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayIndex</c>
	/// labeled alternative in <see cref="openeParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayIndex([NotNull] openeParser.ArrayIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bracket</c>
	/// labeled alternative in <see cref="openeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket([NotNull] openeParser.BracketContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptElement</c>
	/// labeled alternative in <see cref="openeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptElement([NotNull] openeParser.OptElementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryExpr</c>
	/// labeled alternative in <see cref="openeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExpr([NotNull] openeParser.BinaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="openeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] openeParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.data_set_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_set_value([NotNull] openeParser.Data_set_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.datetime_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_value([NotNull] openeParser.Datetime_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.macro_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_value([NotNull] openeParser.Macro_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.func_ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_ptr([NotNull] openeParser.Func_ptrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.bool_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_value([NotNull] openeParser.Bool_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="openeParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] openeParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Float</c>
	/// labeled alternative in <see cref="openeParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] openeParser.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeParser.string_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_value([NotNull] openeParser.String_valueContext context);
}
