//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Project/OpenELanguage/Compiler\opene.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="opene"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IopeneVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.opene"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpene([NotNull] opene.OpeneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.edition_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdition_spec([NotNull] opene.Edition_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.struct_declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declare([NotNull] opene.Struct_declareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.access_level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_level([NotNull] opene.Access_levelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_list([NotNull] opene.Member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.library_list_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_list_opt([NotNull] opene.Library_list_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.library_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_spec([NotNull] opene.Library_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.prog_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set([NotNull] opene.Prog_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.prog_set_variable_decl_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set_variable_decl_opt([NotNull] opene.Prog_set_variable_decl_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.prog_set_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set_variable_decl([NotNull] opene.Prog_set_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_decl([NotNull] opene.Variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.variable_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_comment([NotNull] opene.Variable_commentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.variable_comment_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_comment_element([NotNull] opene.Variable_comment_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.variable_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_name([NotNull] opene.Variable_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.variable_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_type([NotNull] opene.Variable_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.dimension_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimension_decl([NotNull] opene.Dimension_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.sub_program_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_program_opt([NotNull] opene.Sub_program_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.sub_program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_program([NotNull] opene.Sub_programContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.parameter_decl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_decl_list([NotNull] opene.Parameter_decl_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.parameter_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_decl([NotNull] opene.Parameter_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.local_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_decl([NotNull] opene.Local_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] opene.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConditionStatement</c>
	/// labeled alternative in <see cref="opene.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionStatement([NotNull] opene.ConditionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStatement</c>
	/// labeled alternative in <see cref="opene.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] opene.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="opene.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] opene.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LoopStatement</c>
	/// labeled alternative in <see cref="opene.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopStatement([NotNull] opene.LoopStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="opene.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] opene.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="opene.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] opene.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="opene.condition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] opene.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfTrueStmt</c>
	/// labeled alternative in <see cref="opene.condition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfTrueStmt([NotNull] opene.IfTrueStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.condition_statement_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_statement_else([NotNull] opene.Condition_statement_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.hierarchy_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierarchy_identifier([NotNull] opene.Hierarchy_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="opene.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] opene.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallWithArgu</c>
	/// labeled alternative in <see cref="opene.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallWithArgu([NotNull] opene.FuncCallWithArguContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallWithoutArgu</c>
	/// labeled alternative in <see cref="opene.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallWithoutArgu([NotNull] opene.FuncCallWithoutArguContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayIndex</c>
	/// labeled alternative in <see cref="opene.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayIndex([NotNull] opene.ArrayIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bracket</c>
	/// labeled alternative in <see cref="opene.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket([NotNull] opene.BracketContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptElement</c>
	/// labeled alternative in <see cref="opene.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptElement([NotNull] opene.OptElementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryExpr</c>
	/// labeled alternative in <see cref="opene.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExpr([NotNull] opene.BinaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="opene.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] opene.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.macro_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_value([NotNull] opene.Macro_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.func_ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_ptr([NotNull] opene.Func_ptrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.bool_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_value([NotNull] opene.Bool_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="opene.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] opene.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Float</c>
	/// labeled alternative in <see cref="opene.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] opene.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="opene.string_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_value([NotNull] opene.String_valueContext context);
}
