//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Project/OpenELanguage/Compiler\opene.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class openeParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		K_VERSION=10, K_LIBRARY=11, K_PROGRAM_SET=12, K_PROGRAM_SET_VARIABLE=13, 
		K_LOCAL_VARIABLE=14, K_PARAMETER=15, K_SUB_PROGRAM=16, K_IF_TRUE=17, K_IF_TRUE_END=18, 
		K_IF=19, K_ELSE=20, K_END_IF=21, K_WHILE=22, K_WHILE_END=23, K_FOR=24, 
		K_FOR_END=25, K_TRUE=26, K_FALSE=27, K_ADD_OPT=28, K_SUB_OPT=29, K_MUL_OPT=30, 
		K_DIV_OPT=31, K_ASSIGN_OPT=32, K_NOT_EQUAL_OPT=33, K_OR_OPT=34, INTEGER_LITERAL=35, 
		FLOAT_LITERAL=36, IDENTIFIER=37, WHITESPACE=38, NEWLINE=39, STRING_LITERAL=40, 
		CODE_COMMIT=41, OTHER_CHAR=42;
	public const int
		RULE_opene_src = 0, RULE_edition_spec = 1, RULE_library_list_opt = 2, 
		RULE_library_spec = 3, RULE_prog_set = 4, RULE_prog_set_variable_decl_opt = 5, 
		RULE_prog_set_variable_decl = 6, RULE_variable_decl = 7, RULE_variable_comment = 8, 
		RULE_variable_comment_element = 9, RULE_variable_name = 10, RULE_variable_type = 11, 
		RULE_dimension_decl = 12, RULE_sub_program_opt = 13, RULE_sub_program = 14, 
		RULE_parameter_decl_list = 15, RULE_parameter_decl = 16, RULE_local_variable_decl = 17, 
		RULE_statement_list = 18, RULE_statement = 19, RULE_condition_statement = 20, 
		RULE_condition_statement_else = 21, RULE_hierarchy_identifier = 22, RULE_name_component = 23, 
		RULE_expression = 24, RULE_macro_value = 25, RULE_bool_value = 26, RULE_number = 27, 
		RULE_string_value = 28;
	public static readonly string[] ruleNames = {
		"opene_src", "edition_spec", "library_list_opt", "library_spec", "prog_set", 
		"prog_set_variable_decl_opt", "prog_set_variable_decl", "variable_decl", 
		"variable_comment", "variable_comment_element", "variable_name", "variable_type", 
		"dimension_decl", "sub_program_opt", "sub_program", "parameter_decl_list", 
		"parameter_decl", "local_variable_decl", "statement_list", "statement", 
		"condition_statement", "condition_statement_else", "hierarchy_identifier", 
		"name_component", "expression", "macro_value", "bool_value", "number", 
		"string_value"
	};

	private static readonly string[] _LiteralNames = {
		null, "','", "'\"'", "'('", "')'", "'.'", "'['", "']'", "'-'", "'#'", 
		"'.\u7248\u672C'", "'.\u652F\u6301\u5E93'", "'.\u7A0B\u5E8F\u96C6'", "'.\u7A0B\u5E8F\u96C6\u53D8\u91CF'", 
		"'.\u5C40\u90E8\u53D8\u91CF'", "'.\u53C2\u6570'", "'.\u5B50\u7A0B\u5E8F'", 
		"'.\u5982\u679C\u771F'", "'.\u5982\u679C\u771F\u7ED3\u675F'", "'.\u5982\u679C'", 
		"'.\u5426\u5219'", "'.\u5982\u679C\u7ED3\u675F'", "'.\u5224\u65AD\u5FAA\u73AF\u9996'", 
		"'.\u5224\u65AD\u5FAA\u73AF\u5C3E'", "'.\u8BA1\u6B21\u5FAA\u73AF\u9996'", 
		"'.\u8BA1\u6B21\u5FAA\u73AF\u5C3E'", "'\u771F'", "'\u5047'", "'\uFF0B'", 
		"'\uFF0D'", "'\u00D7'", "'\u00F7'", "'\uFF1D'", "'\u2260'", "'\u6216'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "K_VERSION", 
		"K_LIBRARY", "K_PROGRAM_SET", "K_PROGRAM_SET_VARIABLE", "K_LOCAL_VARIABLE", 
		"K_PARAMETER", "K_SUB_PROGRAM", "K_IF_TRUE", "K_IF_TRUE_END", "K_IF", 
		"K_ELSE", "K_END_IF", "K_WHILE", "K_WHILE_END", "K_FOR", "K_FOR_END", 
		"K_TRUE", "K_FALSE", "K_ADD_OPT", "K_SUB_OPT", "K_MUL_OPT", "K_DIV_OPT", 
		"K_ASSIGN_OPT", "K_NOT_EQUAL_OPT", "K_OR_OPT", "INTEGER_LITERAL", "FLOAT_LITERAL", 
		"IDENTIFIER", "WHITESPACE", "NEWLINE", "STRING_LITERAL", "CODE_COMMIT", 
		"OTHER_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "opene.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static openeParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public openeParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public openeParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Opene_srcContext : ParserRuleContext {
		public Edition_specContext edition_spec() {
			return GetRuleContext<Edition_specContext>(0);
		}
		public Library_list_optContext library_list_opt() {
			return GetRuleContext<Library_list_optContext>(0);
		}
		public Prog_setContext prog_set() {
			return GetRuleContext<Prog_setContext>(0);
		}
		public Opene_srcContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_opene_src; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpene_src(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Opene_srcContext opene_src() {
		Opene_srcContext _localctx = new Opene_srcContext(Context, State);
		EnterRule(_localctx, 0, RULE_opene_src);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58; edition_spec();
			State = 59; library_list_opt();
			State = 60; prog_set();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Edition_specContext : ParserRuleContext {
		public ITerminalNode K_VERSION() { return GetToken(openeParser.K_VERSION, 0); }
		public ITerminalNode INTEGER_LITERAL() { return GetToken(openeParser.INTEGER_LITERAL, 0); }
		public Edition_specContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_edition_spec; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEdition_spec(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Edition_specContext edition_spec() {
		Edition_specContext _localctx = new Edition_specContext(Context, State);
		EnterRule(_localctx, 2, RULE_edition_spec);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62; Match(K_VERSION);
			State = 63; Match(INTEGER_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Library_list_optContext : ParserRuleContext {
		public Library_specContext[] library_spec() {
			return GetRuleContexts<Library_specContext>();
		}
		public Library_specContext library_spec(int i) {
			return GetRuleContext<Library_specContext>(i);
		}
		public Library_list_optContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_library_list_opt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLibrary_list_opt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Library_list_optContext library_list_opt() {
		Library_list_optContext _localctx = new Library_list_optContext(Context, State);
		EnterRule(_localctx, 4, RULE_library_list_opt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==K_LIBRARY) {
				{
				{
				State = 65; library_spec();
				}
				}
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Library_specContext : ParserRuleContext {
		public ITerminalNode K_LIBRARY() { return GetToken(openeParser.K_LIBRARY, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public Library_specContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_library_spec; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLibrary_spec(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Library_specContext library_spec() {
		Library_specContext _localctx = new Library_specContext(Context, State);
		EnterRule(_localctx, 6, RULE_library_spec);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71; Match(K_LIBRARY);
			State = 72; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prog_setContext : ParserRuleContext {
		public ITerminalNode K_PROGRAM_SET() { return GetToken(openeParser.K_PROGRAM_SET, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public Prog_set_variable_decl_optContext prog_set_variable_decl_opt() {
			return GetRuleContext<Prog_set_variable_decl_optContext>(0);
		}
		public Sub_program_optContext sub_program_opt() {
			return GetRuleContext<Sub_program_optContext>(0);
		}
		public Prog_setContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog_set; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg_set(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Prog_setContext prog_set() {
		Prog_setContext _localctx = new Prog_setContext(Context, State);
		EnterRule(_localctx, 8, RULE_prog_set);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74; Match(K_PROGRAM_SET);
			State = 75; Match(IDENTIFIER);
			State = 76; prog_set_variable_decl_opt();
			State = 77; sub_program_opt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prog_set_variable_decl_optContext : ParserRuleContext {
		public Prog_set_variable_declContext[] prog_set_variable_decl() {
			return GetRuleContexts<Prog_set_variable_declContext>();
		}
		public Prog_set_variable_declContext prog_set_variable_decl(int i) {
			return GetRuleContext<Prog_set_variable_declContext>(i);
		}
		public Prog_set_variable_decl_optContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog_set_variable_decl_opt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg_set_variable_decl_opt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Prog_set_variable_decl_optContext prog_set_variable_decl_opt() {
		Prog_set_variable_decl_optContext _localctx = new Prog_set_variable_decl_optContext(Context, State);
		EnterRule(_localctx, 10, RULE_prog_set_variable_decl_opt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==K_PROGRAM_SET_VARIABLE) {
				{
				{
				State = 79; prog_set_variable_decl();
				}
				}
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prog_set_variable_declContext : ParserRuleContext {
		public ITerminalNode K_PROGRAM_SET_VARIABLE() { return GetToken(openeParser.K_PROGRAM_SET_VARIABLE, 0); }
		public Variable_declContext variable_decl() {
			return GetRuleContext<Variable_declContext>(0);
		}
		public Prog_set_variable_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog_set_variable_decl; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProg_set_variable_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Prog_set_variable_declContext prog_set_variable_decl() {
		Prog_set_variable_declContext _localctx = new Prog_set_variable_declContext(Context, State);
		EnterRule(_localctx, 12, RULE_prog_set_variable_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85; Match(K_PROGRAM_SET_VARIABLE);
			State = 86; variable_decl();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_declContext : ParserRuleContext {
		public Variable_nameContext variable_name() {
			return GetRuleContext<Variable_nameContext>(0);
		}
		public Variable_typeContext variable_type() {
			return GetRuleContext<Variable_typeContext>(0);
		}
		public Variable_commentContext variable_comment() {
			return GetRuleContext<Variable_commentContext>(0);
		}
		public Dimension_declContext dimension_decl() {
			return GetRuleContext<Dimension_declContext>(0);
		}
		public Variable_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_decl; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_declContext variable_decl() {
		Variable_declContext _localctx = new Variable_declContext(Context, State);
		EnterRule(_localctx, 14, RULE_variable_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88; variable_name();
			State = 89; Match(T__0);
			State = 90; variable_type();
			State = 96;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				{
				State = 91; Match(T__0);
				State = 92; Match(T__0);
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__1) {
					{
					State = 93; dimension_decl();
					}
				}

				}
				break;
			}
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 98; Match(T__0);
				State = 99; variable_comment();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_commentContext : ParserRuleContext {
		public Variable_comment_elementContext[] variable_comment_element() {
			return GetRuleContexts<Variable_comment_elementContext>();
		}
		public Variable_comment_elementContext variable_comment_element(int i) {
			return GetRuleContext<Variable_comment_elementContext>(i);
		}
		public Variable_commentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_comment; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_comment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_commentContext variable_comment() {
		Variable_commentContext _localctx = new Variable_commentContext(Context, State);
		EnterRule(_localctx, 16, RULE_variable_comment);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 102; variable_comment_element();
					}
					} 
				}
				State = 107;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_comment_elementContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public ITerminalNode OTHER_CHAR() { return GetToken(openeParser.OTHER_CHAR, 0); }
		public Variable_comment_elementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_comment_element; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_comment_element(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_comment_elementContext variable_comment_element() {
		Variable_comment_elementContext _localctx = new Variable_comment_elementContext(Context, State);
		EnterRule(_localctx, 18, RULE_variable_comment_element);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			_la = TokenStream.LA(1);
			if ( !(_la==IDENTIFIER || _la==OTHER_CHAR) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_nameContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public Variable_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_name; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_nameContext variable_name() {
		Variable_nameContext _localctx = new Variable_nameContext(Context, State);
		EnterRule(_localctx, 20, RULE_variable_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_typeContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public Variable_typeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_type; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_type(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_typeContext variable_type() {
		Variable_typeContext _localctx = new Variable_typeContext(Context, State);
		EnterRule(_localctx, 22, RULE_variable_type);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Dimension_declContext : ParserRuleContext {
		public ITerminalNode INTEGER_LITERAL() { return GetToken(openeParser.INTEGER_LITERAL, 0); }
		public Dimension_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dimension_decl; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDimension_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Dimension_declContext dimension_decl() {
		Dimension_declContext _localctx = new Dimension_declContext(Context, State);
		EnterRule(_localctx, 24, RULE_dimension_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114; Match(T__1);
			State = 115; Match(INTEGER_LITERAL);
			State = 116; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Sub_program_optContext : ParserRuleContext {
		public Sub_programContext[] sub_program() {
			return GetRuleContexts<Sub_programContext>();
		}
		public Sub_programContext sub_program(int i) {
			return GetRuleContext<Sub_programContext>(i);
		}
		public Sub_program_optContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sub_program_opt; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSub_program_opt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Sub_program_optContext sub_program_opt() {
		Sub_program_optContext _localctx = new Sub_program_optContext(Context, State);
		EnterRule(_localctx, 26, RULE_sub_program_opt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==K_SUB_PROGRAM) {
				{
				{
				State = 118; sub_program();
				}
				}
				State = 123;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Sub_programContext : ParserRuleContext {
		public ITerminalNode K_SUB_PROGRAM() { return GetToken(openeParser.K_SUB_PROGRAM, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public Parameter_decl_listContext parameter_decl_list() {
			return GetRuleContext<Parameter_decl_listContext>(0);
		}
		public Statement_listContext statement_list() {
			return GetRuleContext<Statement_listContext>(0);
		}
		public Variable_typeContext variable_type() {
			return GetRuleContext<Variable_typeContext>(0);
		}
		public Local_variable_declContext[] local_variable_decl() {
			return GetRuleContexts<Local_variable_declContext>();
		}
		public Local_variable_declContext local_variable_decl(int i) {
			return GetRuleContext<Local_variable_declContext>(i);
		}
		public Sub_programContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sub_program; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSub_program(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Sub_programContext sub_program() {
		Sub_programContext _localctx = new Sub_programContext(Context, State);
		EnterRule(_localctx, 28, RULE_sub_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124; Match(K_SUB_PROGRAM);
			State = 125; Match(IDENTIFIER);
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 126; Match(T__0);
				State = 127; variable_type();
				}
			}

			State = 130; parameter_decl_list();
			State = 134;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==K_LOCAL_VARIABLE) {
				{
				{
				State = 131; local_variable_decl();
				}
				}
				State = 136;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 137; statement_list();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Parameter_decl_listContext : ParserRuleContext {
		public Parameter_declContext[] parameter_decl() {
			return GetRuleContexts<Parameter_declContext>();
		}
		public Parameter_declContext parameter_decl(int i) {
			return GetRuleContext<Parameter_declContext>(i);
		}
		public Parameter_decl_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter_decl_list; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter_decl_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Parameter_decl_listContext parameter_decl_list() {
		Parameter_decl_listContext _localctx = new Parameter_decl_listContext(Context, State);
		EnterRule(_localctx, 30, RULE_parameter_decl_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==K_PARAMETER) {
				{
				{
				State = 139; parameter_decl();
				}
				}
				State = 144;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Parameter_declContext : ParserRuleContext {
		public ITerminalNode K_PARAMETER() { return GetToken(openeParser.K_PARAMETER, 0); }
		public Variable_declContext variable_decl() {
			return GetRuleContext<Variable_declContext>(0);
		}
		public Parameter_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter_decl; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Parameter_declContext parameter_decl() {
		Parameter_declContext _localctx = new Parameter_declContext(Context, State);
		EnterRule(_localctx, 32, RULE_parameter_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145; Match(K_PARAMETER);
			State = 146; variable_decl();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Local_variable_declContext : ParserRuleContext {
		public ITerminalNode K_LOCAL_VARIABLE() { return GetToken(openeParser.K_LOCAL_VARIABLE, 0); }
		public Variable_declContext variable_decl() {
			return GetRuleContext<Variable_declContext>(0);
		}
		public Local_variable_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_local_variable_decl; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLocal_variable_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Local_variable_declContext local_variable_decl() {
		Local_variable_declContext _localctx = new Local_variable_declContext(Context, State);
		EnterRule(_localctx, 34, RULE_local_variable_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148; Match(K_LOCAL_VARIABLE);
			State = 149; variable_decl();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_listContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public Statement_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_list; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_listContext statement_list() {
		Statement_listContext _localctx = new Statement_listContext(Context, State);
		EnterRule(_localctx, 36, RULE_statement_list);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 154;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 151; statement();
					}
					} 
				}
				State = 156;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Condition_statementContext condition_statement() {
			return GetRuleContext<Condition_statementContext>(0);
		}
		public Hierarchy_identifierContext hierarchy_identifier() {
			return GetRuleContext<Hierarchy_identifierContext>(0);
		}
		public ITerminalNode K_ASSIGN_OPT() { return GetToken(openeParser.K_ASSIGN_OPT, 0); }
		public ITerminalNode K_WHILE() { return GetToken(openeParser.K_WHILE, 0); }
		public Statement_listContext statement_list() {
			return GetRuleContext<Statement_listContext>(0);
		}
		public ITerminalNode K_WHILE_END() { return GetToken(openeParser.K_WHILE_END, 0); }
		public ITerminalNode K_FOR() { return GetToken(openeParser.K_FOR, 0); }
		public ITerminalNode K_FOR_END() { return GetToken(openeParser.K_FOR_END, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 38, RULE_statement);
		int _la;
		try {
			State = 185;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 157; expression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 158; condition_statement();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 159; hierarchy_identifier();
				State = 160; Match(K_ASSIGN_OPT);
				State = 161; expression(0);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 163; Match(K_WHILE);
				State = 164; Match(T__2);
				State = 165; expression(0);
				State = 166; Match(T__3);
				State = 167; statement_list();
				State = 168; Match(K_WHILE_END);
				State = 169; Match(T__2);
				State = 170; Match(T__3);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 172; Match(K_FOR);
				State = 173; Match(T__2);
				State = 174; expression(0);
				State = 175; Match(T__0);
				State = 177;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__2) | (1L << T__7) | (1L << T__8) | (1L << K_TRUE) | (1L << K_FALSE) | (1L << INTEGER_LITERAL) | (1L << FLOAT_LITERAL) | (1L << IDENTIFIER) | (1L << STRING_LITERAL))) != 0)) {
					{
					State = 176; expression(0);
					}
				}

				State = 179; Match(T__3);
				State = 180; statement_list();
				State = 181; Match(K_FOR_END);
				State = 182; Match(T__2);
				State = 183; Match(T__3);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Condition_statementContext : ParserRuleContext {
		public Condition_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition_statement; } }
	 
		public Condition_statementContext() { }
		public virtual void CopyFrom(Condition_statementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IfStmtContext : Condition_statementContext {
		public ITerminalNode K_IF() { return GetToken(openeParser.K_IF, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Statement_listContext statement_list() {
			return GetRuleContext<Statement_listContext>(0);
		}
		public ITerminalNode K_END_IF() { return GetToken(openeParser.K_END_IF, 0); }
		public Condition_statement_elseContext condition_statement_else() {
			return GetRuleContext<Condition_statement_elseContext>(0);
		}
		public IfStmtContext(Condition_statementContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfStmt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IfTrueStmtContext : Condition_statementContext {
		public ITerminalNode[] K_IF_TRUE_END() { return GetTokens(openeParser.K_IF_TRUE_END); }
		public ITerminalNode K_IF_TRUE_END(int i) {
			return GetToken(openeParser.K_IF_TRUE_END, i);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Statement_listContext statement_list() {
			return GetRuleContext<Statement_listContext>(0);
		}
		public IfTrueStmtContext(Condition_statementContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfTrueStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Condition_statementContext condition_statement() {
		Condition_statementContext _localctx = new Condition_statementContext(Context, State);
		EnterRule(_localctx, 40, RULE_condition_statement);
		int _la;
		try {
			State = 204;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case K_IF:
				_localctx = new IfStmtContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 187; Match(K_IF);
				State = 188; Match(T__2);
				State = 189; expression(0);
				State = 190; Match(T__3);
				State = 191; statement_list();
				State = 193;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==K_ELSE) {
					{
					State = 192; condition_statement_else();
					}
				}

				State = 195; Match(K_END_IF);
				}
				break;
			case K_IF_TRUE_END:
				_localctx = new IfTrueStmtContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 197; Match(K_IF_TRUE_END);
				State = 198; Match(T__2);
				State = 199; expression(0);
				State = 200; Match(T__3);
				State = 201; statement_list();
				State = 202; Match(K_IF_TRUE_END);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Condition_statement_elseContext : ParserRuleContext {
		public ITerminalNode K_ELSE() { return GetToken(openeParser.K_ELSE, 0); }
		public Statement_listContext statement_list() {
			return GetRuleContext<Statement_listContext>(0);
		}
		public Condition_statement_elseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition_statement_else; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition_statement_else(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Condition_statement_elseContext condition_statement_else() {
		Condition_statement_elseContext _localctx = new Condition_statement_elseContext(Context, State);
		EnterRule(_localctx, 42, RULE_condition_statement_else);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206; Match(K_ELSE);
			State = 207; statement_list();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Hierarchy_identifierContext : ParserRuleContext {
		public Name_componentContext[] name_component() {
			return GetRuleContexts<Name_componentContext>();
		}
		public Name_componentContext name_component(int i) {
			return GetRuleContext<Name_componentContext>(i);
		}
		public Hierarchy_identifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hierarchy_identifier; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHierarchy_identifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Hierarchy_identifierContext hierarchy_identifier() {
		Hierarchy_identifierContext _localctx = new Hierarchy_identifierContext(Context, State);
		EnterRule(_localctx, 44, RULE_hierarchy_identifier);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 209; name_component();
			State = 214;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 210; Match(T__4);
					State = 211; name_component();
					}
					} 
				}
				State = 216;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_componentContext : ParserRuleContext {
		public Name_componentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_component; } }
	 
		public Name_componentContext() { }
		public virtual void CopyFrom(Name_componentContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IdentifierContext : Name_componentContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public IdentifierContext(Name_componentContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncCallWithArguContext : Name_componentContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public FuncCallWithArguContext(Name_componentContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCallWithArgu(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncCallWithoutArguContext : Name_componentContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public FuncCallWithoutArguContext(Name_componentContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCallWithoutArgu(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ArrayIndexContext : Name_componentContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ArrayIndexContext(Name_componentContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayIndex(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Name_componentContext name_component() {
		Name_componentContext _localctx = new Name_componentContext(Context, State);
		EnterRule(_localctx, 46, RULE_name_component);
		int _la;
		try {
			State = 240;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				_localctx = new IdentifierContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 217; Match(IDENTIFIER);
				}
				break;
			case 2:
				_localctx = new FuncCallWithoutArguContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 218; Match(IDENTIFIER);
				State = 219; Match(T__2);
				State = 220; Match(T__3);
				}
				break;
			case 3:
				_localctx = new FuncCallWithArguContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 221; Match(IDENTIFIER);
				State = 222; Match(T__2);
				State = 223; expression(0);
				State = 230;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__0) {
					{
					{
					State = 224; Match(T__0);
					State = 226;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__2) | (1L << T__7) | (1L << T__8) | (1L << K_TRUE) | (1L << K_FALSE) | (1L << INTEGER_LITERAL) | (1L << FLOAT_LITERAL) | (1L << IDENTIFIER) | (1L << STRING_LITERAL))) != 0)) {
						{
						State = 225; expression(0);
						}
					}

					}
					}
					State = 232;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 233; Match(T__3);
				}
				break;
			case 4:
				_localctx = new ArrayIndexContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 235; Match(IDENTIFIER);
				State = 236; Match(T__5);
				State = 237; expression(0);
				State = 238; Match(T__6);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BracketContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public BracketContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBracket(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OptElementContext : ExpressionContext {
		public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public Bool_valueContext bool_value() {
			return GetRuleContext<Bool_valueContext>(0);
		}
		public Macro_valueContext macro_value() {
			return GetRuleContext<Macro_valueContext>(0);
		}
		public String_valueContext string_value() {
			return GetRuleContext<String_valueContext>(0);
		}
		public Hierarchy_identifierContext hierarchy_identifier() {
			return GetRuleContext<Hierarchy_identifierContext>(0);
		}
		public OptElementContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOptElement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryExprContext : ExpressionContext {
		public IToken opt;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode K_ADD_OPT() { return GetToken(openeParser.K_ADD_OPT, 0); }
		public ITerminalNode K_SUB_OPT() { return GetToken(openeParser.K_SUB_OPT, 0); }
		public ITerminalNode K_MUL_OPT() { return GetToken(openeParser.K_MUL_OPT, 0); }
		public ITerminalNode K_DIV_OPT() { return GetToken(openeParser.K_DIV_OPT, 0); }
		public ITerminalNode K_ASSIGN_OPT() { return GetToken(openeParser.K_ASSIGN_OPT, 0); }
		public ITerminalNode K_NOT_EQUAL_OPT() { return GetToken(openeParser.K_NOT_EQUAL_OPT, 0); }
		public ITerminalNode K_OR_OPT() { return GetToken(openeParser.K_OR_OPT, 0); }
		public BinaryExprContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryExprContext : ExpressionContext {
		public IToken opt;
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public UnaryExprContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 48;
		EnterRecursionRule(_localctx, 48, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 254;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__2:
				{
				_localctx = new BracketContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 243; Match(T__2);
				State = 244; expression(0);
				State = 245; Match(T__3);
				}
				break;
			case T__7:
				{
				_localctx = new UnaryExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 247; ((UnaryExprContext)_localctx).opt = Match(T__7);
				State = 248; expression(13);
				}
				break;
			case INTEGER_LITERAL:
			case FLOAT_LITERAL:
				{
				_localctx = new OptElementContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 249; number();
				}
				break;
			case K_TRUE:
			case K_FALSE:
				{
				_localctx = new OptElementContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 250; bool_value();
				}
				break;
			case T__8:
				{
				_localctx = new OptElementContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 251; macro_value();
				}
				break;
			case STRING_LITERAL:
				{
				_localctx = new OptElementContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 252; string_value();
				}
				break;
			case IDENTIFIER:
				{
				_localctx = new OptElementContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 253; hierarchy_identifier();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 279;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 277;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
					case 1:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 256;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 257; ((BinaryExprContext)_localctx).opt = Match(K_ADD_OPT);
						State = 258; expression(13);
						}
						break;
					case 2:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 259;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 260; ((BinaryExprContext)_localctx).opt = Match(K_SUB_OPT);
						State = 261; expression(12);
						}
						break;
					case 3:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 262;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 263; ((BinaryExprContext)_localctx).opt = Match(K_MUL_OPT);
						State = 264; expression(11);
						}
						break;
					case 4:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 265;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 266; ((BinaryExprContext)_localctx).opt = Match(K_DIV_OPT);
						State = 267; expression(10);
						}
						break;
					case 5:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 268;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 269; ((BinaryExprContext)_localctx).opt = Match(K_ASSIGN_OPT);
						State = 270; expression(9);
						}
						break;
					case 6:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 271;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 272; ((BinaryExprContext)_localctx).opt = Match(K_NOT_EQUAL_OPT);
						State = 273; expression(8);
						}
						break;
					case 7:
						{
						_localctx = new BinaryExprContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 274;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 275; ((BinaryExprContext)_localctx).opt = Match(K_OR_OPT);
						State = 276; expression(7);
						}
						break;
					}
					} 
				}
				State = 281;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Macro_valueContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(openeParser.IDENTIFIER, 0); }
		public Macro_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_macro_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMacro_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Macro_valueContext macro_value() {
		Macro_valueContext _localctx = new Macro_valueContext(Context, State);
		EnterRule(_localctx, 50, RULE_macro_value);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 282; Match(T__8);
			State = 283; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Bool_valueContext : ParserRuleContext {
		public IToken bval;
		public ITerminalNode K_TRUE() { return GetToken(openeParser.K_TRUE, 0); }
		public ITerminalNode K_FALSE() { return GetToken(openeParser.K_FALSE, 0); }
		public Bool_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bool_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBool_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Bool_valueContext bool_value() {
		Bool_valueContext _localctx = new Bool_valueContext(Context, State);
		EnterRule(_localctx, 52, RULE_bool_value);
		try {
			State = 287;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case K_TRUE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 285; _localctx.bval = Match(K_TRUE);
				}
				break;
			case K_FALSE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 286; _localctx.bval = Match(K_FALSE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
	 
		public NumberContext() { }
		public virtual void CopyFrom(NumberContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FloatContext : NumberContext {
		public ITerminalNode FLOAT_LITERAL() { return GetToken(openeParser.FLOAT_LITERAL, 0); }
		public FloatContext(NumberContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFloat(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntContext : NumberContext {
		public ITerminalNode INTEGER_LITERAL() { return GetToken(openeParser.INTEGER_LITERAL, 0); }
		public IntContext(NumberContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 54, RULE_number);
		try {
			State = 291;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTEGER_LITERAL:
				_localctx = new IntContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 289; Match(INTEGER_LITERAL);
				}
				break;
			case FLOAT_LITERAL:
				_localctx = new FloatContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 290; Match(FLOAT_LITERAL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class String_valueContext : ParserRuleContext {
		public ITerminalNode STRING_LITERAL() { return GetToken(openeParser.STRING_LITERAL, 0); }
		public String_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IopeneVisitor<TResult> typedVisitor = visitor as IopeneVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public String_valueContext string_value() {
		String_valueContext _localctx = new String_valueContext(Context, State);
		EnterRule(_localctx, 56, RULE_string_value);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 293; Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 24: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 12);
		case 1: return Precpred(Context, 11);
		case 2: return Precpred(Context, 10);
		case 3: return Precpred(Context, 9);
		case 4: return Precpred(Context, 8);
		case 5: return Precpred(Context, 7);
		case 6: return Precpred(Context, 6);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', ',', '\x12A', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\a', '\x4', '\x45', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 'H', 
		'\v', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\a', '\a', 
		'S', '\n', '\a', '\f', '\a', '\xE', '\a', 'V', '\v', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x61', '\n', '\t', '\x5', 
		'\t', '\x63', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 'g', 
		'\n', '\t', '\x3', '\n', '\a', '\n', 'j', '\n', '\n', '\f', '\n', '\xE', 
		'\n', 'm', '\v', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\a', '\xF', 'z', '\n', '\xF', '\f', '\xF', '\xE', 
		'\xF', '}', '\v', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x5', '\x10', '\x83', '\n', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\a', '\x10', '\x87', '\n', '\x10', '\f', '\x10', '\xE', '\x10', 
		'\x8A', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\a', 
		'\x11', '\x8F', '\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x92', '\v', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x14', '\a', '\x14', '\x9B', '\n', '\x14', 
		'\f', '\x14', '\xE', '\x14', '\x9E', '\v', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xB4', 
		'\n', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xBC', '\n', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x5', '\x16', '\xC4', '\n', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\xCF', '\n', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\a', '\x18', '\xD7', '\n', '\x18', '\f', '\x18', '\xE', '\x18', 
		'\xDA', '\v', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x5', '\x19', '\xE5', '\n', '\x19', '\a', '\x19', '\xE7', '\n', 
		'\x19', '\f', '\x19', '\xE', '\x19', '\xEA', '\v', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x5', '\x19', '\xF3', '\n', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x5', '\x1A', '\x101', '\n', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', 
		'\x118', '\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\x11B', '\v', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', 
		'\x5', '\x1C', '\x122', '\n', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x5', 
		'\x1D', '\x126', '\n', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', 
		'\x2', '\x3', '\x32', '\x1F', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', 
		'\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', 
		'$', '&', '(', '*', ',', '.', '\x30', '\x32', '\x34', '\x36', '\x38', 
		':', '\x2', '\x3', '\x4', '\x2', '\'', '\'', ',', ',', '\x2', '\x133', 
		'\x2', '<', '\x3', '\x2', '\x2', '\x2', '\x4', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '\x46', '\x3', '\x2', '\x2', '\x2', '\b', 'I', '\x3', '\x2', 
		'\x2', '\x2', '\n', 'L', '\x3', '\x2', '\x2', '\x2', '\f', 'T', '\x3', 
		'\x2', '\x2', '\x2', '\xE', 'W', '\x3', '\x2', '\x2', '\x2', '\x10', 'Z', 
		'\x3', '\x2', '\x2', '\x2', '\x12', 'k', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'n', '\x3', '\x2', '\x2', '\x2', '\x16', 'p', '\x3', '\x2', '\x2', '\x2', 
		'\x18', 'r', '\x3', '\x2', '\x2', '\x2', '\x1A', 't', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '{', '\x3', '\x2', '\x2', '\x2', '\x1E', '~', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\x90', '\x3', '\x2', '\x2', '\x2', '\"', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '$', '\x96', '\x3', '\x2', '\x2', '\x2', '&', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '(', '\xBB', '\x3', '\x2', '\x2', '\x2', '*', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', ',', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '.', '\xD3', '\x3', '\x2', '\x2', '\x2', '\x30', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\x100', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x11C', '\x3', '\x2', '\x2', '\x2', '\x36', '\x121', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x125', '\x3', '\x2', '\x2', '\x2', ':', '\x127', '\x3', 
		'\x2', '\x2', '\x2', '<', '=', '\x5', '\x4', '\x3', '\x2', '=', '>', '\x5', 
		'\x6', '\x4', '\x2', '>', '?', '\x5', '\n', '\x6', '\x2', '?', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x41', '\a', '\f', '\x2', '\x2', '\x41', 
		'\x42', '\a', '%', '\x2', '\x2', '\x42', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x45', '\x5', '\b', '\x5', '\x2', '\x44', '\x43', '\x3', '\x2', 
		'\x2', '\x2', '\x45', 'H', '\x3', '\x2', '\x2', '\x2', '\x46', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\x3', '\x2', '\x2', '\x2', 'G', 
		'\a', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\a', '\r', '\x2', '\x2', 'J', 'K', '\a', '\'', '\x2', '\x2', 
		'K', '\t', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '\xE', '\x2', '\x2', 
		'M', 'N', '\a', '\'', '\x2', '\x2', 'N', 'O', '\x5', '\f', '\a', '\x2', 
		'O', 'P', '\x5', '\x1C', '\xF', '\x2', 'P', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'S', '\x5', '\xE', '\b', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'V', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\x3', '\x2', '\x2', '\x2', 'U', '\r', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '\xF', 
		'\x2', '\x2', 'X', 'Y', '\x5', '\x10', '\t', '\x2', 'Y', '\xF', '\x3', 
		'\x2', '\x2', '\x2', 'Z', '[', '\x5', '\x16', '\f', '\x2', '[', '\\', 
		'\a', '\x3', '\x2', '\x2', '\\', '\x62', '\x5', '\x18', '\r', '\x2', ']', 
		'^', '\a', '\x3', '\x2', '\x2', '^', '`', '\a', '\x3', '\x2', '\x2', '_', 
		'\x61', '\x5', '\x1A', '\xE', '\x2', '`', '_', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\x62', ']', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x63', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x65', '\a', '\x3', '\x2', '\x2', '\x65', 'g', '\x5', '\x12', 
		'\n', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', 
		'\x3', '\x2', '\x2', '\x2', 'g', '\x11', '\x3', '\x2', '\x2', '\x2', 'h', 
		'j', '\x5', '\x14', '\v', '\x2', 'i', 'h', '\x3', '\x2', '\x2', '\x2', 
		'j', 'm', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'k', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\t', '\x2', '\x2', 
		'\x2', 'o', '\x15', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\'', 
		'\x2', '\x2', 'q', '\x17', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', 
		'\'', '\x2', '\x2', 's', '\x19', '\x3', '\x2', '\x2', '\x2', 't', 'u', 
		'\a', '\x4', '\x2', '\x2', 'u', 'v', '\a', '%', '\x2', '\x2', 'v', 'w', 
		'\a', '\x4', '\x2', '\x2', 'w', '\x1B', '\x3', '\x2', '\x2', '\x2', 'x', 
		'z', '\x5', '\x1E', '\x10', '\x2', 'y', 'x', '\x3', '\x2', '\x2', '\x2', 
		'z', '}', '\x3', '\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', 
		'{', '|', '\x3', '\x2', '\x2', '\x2', '|', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '}', '{', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', '\x12', 
		'\x2', '\x2', '\x7F', '\x82', '\a', '\'', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\x3', '\x2', '\x2', '\x81', '\x83', '\x5', '\x18', '\r', '\x2', 
		'\x82', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', '\x88', 
		'\x5', ' ', '\x11', '\x2', '\x85', '\x87', '\x5', '$', '\x13', '\x2', 
		'\x86', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x8A', '\x3', '\x2', 
		'\x2', '\x2', '\x88', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x5', '&', 
		'\x14', '\x2', '\x8C', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8F', 
		'\x5', '\"', '\x12', '\x2', '\x8E', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x92', '\x3', '\x2', '\x2', '\x2', '\x90', '\x8E', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '!', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x94', '\a', '\x11', '\x2', '\x2', '\x94', '\x95', '\x5', '\x10', 
		'\t', '\x2', '\x95', '#', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', 
		'\a', '\x10', '\x2', '\x2', '\x97', '\x98', '\x5', '\x10', '\t', '\x2', 
		'\x98', '%', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\x5', '(', '\x15', 
		'\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xBC', '\x5', 
		'\x32', '\x1A', '\x2', '\xA0', '\xBC', '\x5', '*', '\x16', '\x2', '\xA1', 
		'\xA2', '\x5', '.', '\x18', '\x2', '\xA2', '\xA3', '\a', '\"', '\x2', 
		'\x2', '\xA3', '\xA4', '\x5', '\x32', '\x1A', '\x2', '\xA4', '\xBC', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x18', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', '\x5', '\x2', '\x2', '\xA7', '\xA8', '\x5', '\x32', '\x1A', 
		'\x2', '\xA8', '\xA9', '\a', '\x6', '\x2', '\x2', '\xA9', '\xAA', '\x5', 
		'&', '\x14', '\x2', '\xAA', '\xAB', '\a', '\x19', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', '\x5', '\x2', '\x2', '\xAC', '\xAD', '\a', '\x6', '\x2', 
		'\x2', '\xAD', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', 
		'\x1A', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x5', '\x2', '\x2', '\xB0', 
		'\xB1', '\x5', '\x32', '\x1A', '\x2', '\xB1', '\xB3', '\a', '\x3', '\x2', 
		'\x2', '\xB2', '\xB4', '\x5', '\x32', '\x1A', '\x2', '\xB3', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', '\x6', '\x2', 
		'\x2', '\xB6', '\xB7', '\x5', '&', '\x14', '\x2', '\xB7', '\xB8', '\a', 
		'\x1B', '\x2', '\x2', '\xB8', '\xB9', '\a', '\x5', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', '\x6', '\x2', '\x2', '\xBA', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', ')', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBE', '\a', 
		'\x15', '\x2', '\x2', '\xBE', '\xBF', '\a', '\x5', '\x2', '\x2', '\xBF', 
		'\xC0', '\x5', '\x32', '\x1A', '\x2', '\xC0', '\xC1', '\a', '\x6', '\x2', 
		'\x2', '\xC1', '\xC3', '\x5', '&', '\x14', '\x2', '\xC2', '\xC4', '\x5', 
		',', '\x17', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC6', '\a', '\x17', '\x2', '\x2', '\xC6', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', '\xC8', '\a', '\x14', '\x2', '\x2', '\xC8', 
		'\xC9', '\a', '\x5', '\x2', '\x2', '\xC9', '\xCA', '\x5', '\x32', '\x1A', 
		'\x2', '\xCA', '\xCB', '\a', '\x6', '\x2', '\x2', '\xCB', '\xCC', '\x5', 
		'&', '\x14', '\x2', '\xCC', '\xCD', '\a', '\x14', '\x2', '\x2', '\xCD', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xCF', '+', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD1', '\a', '\x16', '\x2', '\x2', '\xD1', 
		'\xD2', '\x5', '&', '\x14', '\x2', '\xD2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\xD3', '\xD8', '\x5', '\x30', '\x19', '\x2', '\xD4', '\xD5', '\a', '\a', 
		'\x2', '\x2', '\xD5', '\xD7', '\x5', '\x30', '\x19', '\x2', '\xD6', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', '\xD7', '\xDA', '\x3', '\x2', '\x2', '\x2', 
		'\xD8', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\xD9', '/', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xD8', 
		'\x3', '\x2', '\x2', '\x2', '\xDB', '\xF3', '\a', '\'', '\x2', '\x2', 
		'\xDC', '\xDD', '\a', '\'', '\x2', '\x2', '\xDD', '\xDE', '\a', '\x5', 
		'\x2', '\x2', '\xDE', '\xF3', '\a', '\x6', '\x2', '\x2', '\xDF', '\xE0', 
		'\a', '\'', '\x2', '\x2', '\xE0', '\xE1', '\a', '\x5', '\x2', '\x2', '\xE1', 
		'\xE8', '\x5', '\x32', '\x1A', '\x2', '\xE2', '\xE4', '\a', '\x3', '\x2', 
		'\x2', '\xE3', '\xE5', '\x5', '\x32', '\x1A', '\x2', '\xE4', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '\xE4', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE7', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE6', '\x3', 
		'\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xE8', '\x3', '\x2', '\x2', 
		'\x2', '\xEB', '\xEC', '\a', '\x6', '\x2', '\x2', '\xEC', '\xF3', '\x3', 
		'\x2', '\x2', '\x2', '\xED', '\xEE', '\a', '\'', '\x2', '\x2', '\xEE', 
		'\xEF', '\a', '\b', '\x2', '\x2', '\xEF', '\xF0', '\x5', '\x32', '\x1A', 
		'\x2', '\xF0', '\xF1', '\a', '\t', '\x2', '\x2', '\xF1', '\xF3', '\x3', 
		'\x2', '\x2', '\x2', '\xF2', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xF2', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xDF', '\x3', '\x2', '\x2', 
		'\x2', '\xF2', '\xED', '\x3', '\x2', '\x2', '\x2', '\xF3', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\xF4', '\xF5', '\b', '\x1A', '\x1', '\x2', '\xF5', 
		'\xF6', '\a', '\x5', '\x2', '\x2', '\xF6', '\xF7', '\x5', '\x32', '\x1A', 
		'\x2', '\xF7', '\xF8', '\a', '\x6', '\x2', '\x2', '\xF8', '\x101', '\x3', 
		'\x2', '\x2', '\x2', '\xF9', '\xFA', '\a', '\n', '\x2', '\x2', '\xFA', 
		'\x101', '\x5', '\x32', '\x1A', '\xF', '\xFB', '\x101', '\x5', '\x38', 
		'\x1D', '\x2', '\xFC', '\x101', '\x5', '\x36', '\x1C', '\x2', '\xFD', 
		'\x101', '\x5', '\x34', '\x1B', '\x2', '\xFE', '\x101', '\x5', ':', '\x1E', 
		'\x2', '\xFF', '\x101', '\x5', '.', '\x18', '\x2', '\x100', '\xF4', '\x3', 
		'\x2', '\x2', '\x2', '\x100', '\xF9', '\x3', '\x2', '\x2', '\x2', '\x100', 
		'\xFB', '\x3', '\x2', '\x2', '\x2', '\x100', '\xFC', '\x3', '\x2', '\x2', 
		'\x2', '\x100', '\xFD', '\x3', '\x2', '\x2', '\x2', '\x100', '\xFE', '\x3', 
		'\x2', '\x2', '\x2', '\x100', '\xFF', '\x3', '\x2', '\x2', '\x2', '\x101', 
		'\x119', '\x3', '\x2', '\x2', '\x2', '\x102', '\x103', '\f', '\xE', '\x2', 
		'\x2', '\x103', '\x104', '\a', '\x1E', '\x2', '\x2', '\x104', '\x118', 
		'\x5', '\x32', '\x1A', '\xF', '\x105', '\x106', '\f', '\r', '\x2', '\x2', 
		'\x106', '\x107', '\a', '\x1F', '\x2', '\x2', '\x107', '\x118', '\x5', 
		'\x32', '\x1A', '\xE', '\x108', '\x109', '\f', '\f', '\x2', '\x2', '\x109', 
		'\x10A', '\a', ' ', '\x2', '\x2', '\x10A', '\x118', '\x5', '\x32', '\x1A', 
		'\r', '\x10B', '\x10C', '\f', '\v', '\x2', '\x2', '\x10C', '\x10D', '\a', 
		'!', '\x2', '\x2', '\x10D', '\x118', '\x5', '\x32', '\x1A', '\f', '\x10E', 
		'\x10F', '\f', '\n', '\x2', '\x2', '\x10F', '\x110', '\a', '\"', '\x2', 
		'\x2', '\x110', '\x118', '\x5', '\x32', '\x1A', '\v', '\x111', '\x112', 
		'\f', '\t', '\x2', '\x2', '\x112', '\x113', '\a', '#', '\x2', '\x2', '\x113', 
		'\x118', '\x5', '\x32', '\x1A', '\n', '\x114', '\x115', '\f', '\b', '\x2', 
		'\x2', '\x115', '\x116', '\a', '$', '\x2', '\x2', '\x116', '\x118', '\x5', 
		'\x32', '\x1A', '\t', '\x117', '\x102', '\x3', '\x2', '\x2', '\x2', '\x117', 
		'\x105', '\x3', '\x2', '\x2', '\x2', '\x117', '\x108', '\x3', '\x2', '\x2', 
		'\x2', '\x117', '\x10B', '\x3', '\x2', '\x2', '\x2', '\x117', '\x10E', 
		'\x3', '\x2', '\x2', '\x2', '\x117', '\x111', '\x3', '\x2', '\x2', '\x2', 
		'\x117', '\x114', '\x3', '\x2', '\x2', '\x2', '\x118', '\x11B', '\x3', 
		'\x2', '\x2', '\x2', '\x119', '\x117', '\x3', '\x2', '\x2', '\x2', '\x119', 
		'\x11A', '\x3', '\x2', '\x2', '\x2', '\x11A', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x11B', '\x119', '\x3', '\x2', '\x2', '\x2', '\x11C', '\x11D', 
		'\a', '\v', '\x2', '\x2', '\x11D', '\x11E', '\a', '\'', '\x2', '\x2', 
		'\x11E', '\x35', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x122', '\a', '\x1C', 
		'\x2', '\x2', '\x120', '\x122', '\a', '\x1D', '\x2', '\x2', '\x121', '\x11F', 
		'\x3', '\x2', '\x2', '\x2', '\x121', '\x120', '\x3', '\x2', '\x2', '\x2', 
		'\x122', '\x37', '\x3', '\x2', '\x2', '\x2', '\x123', '\x126', '\a', '%', 
		'\x2', '\x2', '\x124', '\x126', '\a', '&', '\x2', '\x2', '\x125', '\x123', 
		'\x3', '\x2', '\x2', '\x2', '\x125', '\x124', '\x3', '\x2', '\x2', '\x2', 
		'\x126', '\x39', '\x3', '\x2', '\x2', '\x2', '\x127', '\x128', '\a', '*', 
		'\x2', '\x2', '\x128', ';', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x46', 
		'T', '`', '\x62', '\x66', 'k', '{', '\x82', '\x88', '\x90', '\x9C', '\xB3', 
		'\xBB', '\xC3', '\xCE', '\xD8', '\xE4', '\xE8', '\xF2', '\x100', '\x117', 
		'\x119', '\x121', '\x125',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
