//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Project/OpenELanguage/Compiler\opene.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class openeLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		K_VERSION=10, K_LIBRARY=11, K_PROGRAM_SET=12, K_PROGRAM_SET_VARIABLE=13, 
		K_LOCAL_VARIABLE=14, K_PARAMETER=15, K_SUB_PROGRAM=16, K_IF_TRUE=17, K_IF_TRUE_END=18, 
		K_IF=19, K_ELSE=20, K_END_IF=21, K_WHILE=22, K_WHILE_END=23, K_FOR=24, 
		K_FOR_END=25, K_ADD_OPT=26, K_SUB_OPT=27, K_MUL_OPT=28, K_DIV_OPT=29, 
		K_ASSIGN_OPT=30, K_NOT_EQUAL_OPT=31, K_OR_OPT=32, INTEGER_LITERAL=33, 
		FLOAT_LITERAL=34, IDENTIFIER=35, WHITESPACE=36, NEWLINE=37, STRING_LITERAL=38, 
		CODE_COMMIT=39, OTHER_CHAR=40;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"K_VERSION", "K_LIBRARY", "K_PROGRAM_SET", "K_PROGRAM_SET_VARIABLE", "K_LOCAL_VARIABLE", 
		"K_PARAMETER", "K_SUB_PROGRAM", "K_IF_TRUE", "K_IF_TRUE_END", "K_IF", 
		"K_ELSE", "K_END_IF", "K_WHILE", "K_WHILE_END", "K_FOR", "K_FOR_END", 
		"K_ADD_OPT", "K_SUB_OPT", "K_MUL_OPT", "K_DIV_OPT", "K_ASSIGN_OPT", "K_NOT_EQUAL_OPT", 
		"K_OR_OPT", "INTEGER_LITERAL", "FLOAT_LITERAL", "UNICODE_CHAR", "IDENTIFIER", 
		"WHITESPACE", "NEWLINE", "STRING_LITERAL", "CODE_COMMIT", "OTHER_CHAR"
	};


	public openeLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public openeLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "','", "'\"'", "'('", "')'", "'.'", "'['", "']'", "'-'", "'#'", 
		"'.\u7248\u672C'", "'.\u652F\u6301\u5E93'", "'.\u7A0B\u5E8F\u96C6'", "'.\u7A0B\u5E8F\u96C6\u53D8\u91CF'", 
		"'.\u5C40\u90E8\u53D8\u91CF'", "'.\u53C2\u6570'", "'.\u5B50\u7A0B\u5E8F'", 
		"'.\u5982\u679C\u771F'", "'.\u5982\u679C\u771F\u7ED3\u675F'", "'.\u5982\u679C'", 
		"'.\u5426\u5219'", "'.\u5982\u679C\u7ED3\u675F'", "'.\u5224\u65AD\u5FAA\u73AF\u9996'", 
		"'.\u5224\u65AD\u5FAA\u73AF\u5C3E'", "'.\u8BA1\u6B21\u5FAA\u73AF\u9996'", 
		"'.\u8BA1\u6B21\u5FAA\u73AF\u5C3E'", "'\uFF0B'", "'\uFF0D'", "'\u00D7'", 
		"'\u00F7'", "'\uFF1D'", "'\u2260'", "'\u6216'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "K_VERSION", 
		"K_LIBRARY", "K_PROGRAM_SET", "K_PROGRAM_SET_VARIABLE", "K_LOCAL_VARIABLE", 
		"K_PARAMETER", "K_SUB_PROGRAM", "K_IF_TRUE", "K_IF_TRUE_END", "K_IF", 
		"K_ELSE", "K_END_IF", "K_WHILE", "K_WHILE_END", "K_FOR", "K_FOR_END", 
		"K_ADD_OPT", "K_SUB_OPT", "K_MUL_OPT", "K_DIV_OPT", "K_ASSIGN_OPT", "K_NOT_EQUAL_OPT", 
		"K_OR_OPT", "INTEGER_LITERAL", "FLOAT_LITERAL", "IDENTIFIER", "WHITESPACE", 
		"NEWLINE", "STRING_LITERAL", "CODE_COMMIT", "OTHER_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "opene.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static openeLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '*', '\x10F', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x3', '!', '\x3', '\"', '\x6', '\"', '\xD1', '\n', '\"', '\r', '\"', 
		'\xE', '\"', '\xD2', '\x3', '#', '\x5', '#', '\xD6', '\n', '#', '\x3', 
		'#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '#', '\x5', '#', '\xDD', 
		'\n', '#', '\x5', '#', '\xDF', '\n', '#', '\x3', '$', '\x3', '$', '\x3', 
		'%', '\x3', '%', '\x6', '%', '\xE5', '\n', '%', '\r', '%', '\xE', '%', 
		'\xE6', '\x3', '&', '\x6', '&', '\xEA', '\n', '&', '\r', '&', '\xE', '&', 
		'\xEB', '\x3', '&', '\x3', '&', '\x3', '\'', '\x5', '\'', '\xF1', '\n', 
		'\'', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x3', '(', 
		'\x3', '(', '\a', '(', '\xF9', '\n', '(', '\f', '(', '\xE', '(', '\xFC', 
		'\v', '(', '\x3', '(', '\x3', '(', '\x3', ')', '\x3', ')', '\a', ')', 
		'\x102', '\n', ')', '\f', ')', '\xE', ')', '\x105', '\v', ')', '\x3', 
		')', '\x5', ')', '\x108', '\n', ')', '\x3', ')', '\x3', ')', '\x3', ')', 
		'\x3', ')', '\x3', '*', '\x3', '*', '\x4', '\xFA', '\x103', '\x2', '+', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', 
		'\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', 
		'\x43', '#', '\x45', '$', 'G', '\x2', 'I', '%', 'K', '&', 'M', '\'', 'O', 
		'(', 'Q', ')', 'S', '*', '\x3', '\x2', '\x5', '\x4', '\x2', '\x4E02', 
		'\x9FA7', '\xF902', '\xFA2F', '\x6', '\x2', '\x32', ';', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', 
		'\x118', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', '\x2', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'S', '\x3', '\x2', '\x2', '\x2', '\x3', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x5', 'W', '\x3', '\x2', '\x2', '\x2', '\a', 'Y', 
		'\x3', '\x2', '\x2', '\x2', '\t', '[', '\x3', '\x2', '\x2', '\x2', '\v', 
		']', '\x3', '\x2', '\x2', '\x2', '\r', '_', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x61', '\x3', '\x2', '\x2', '\x2', '\x11', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x65', '\x3', '\x2', '\x2', '\x2', '\x15', 'g', 
		'\x3', '\x2', '\x2', '\x2', '\x17', 'k', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'p', '\x3', '\x2', '\x2', '\x2', '\x1B', 'u', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '|', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x86', '\x3', '\x2', '\x2', '\x2', '#', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '%', '\x90', '\x3', '\x2', '\x2', '\x2', '\'', '\x97', 
		'\x3', '\x2', '\x2', '\x2', ')', '\x9B', '\x3', '\x2', '\x2', '\x2', '+', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '-', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '/', '\xAC', '\x3', '\x2', '\x2', '\x2', '\x31', '\xB3', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\xBA', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\x37', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\xC5', '\x3', '\x2', '\x2', '\x2', ';', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '=', '\xC9', '\x3', '\x2', '\x2', '\x2', '?', '\xCB', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\xCD', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\xD0', '\x3', '\x2', '\x2', '\x2', '\x45', '\xDE', '\x3', '\x2', 
		'\x2', '\x2', 'G', '\xE0', '\x3', '\x2', '\x2', '\x2', 'I', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', 'K', '\xE9', '\x3', '\x2', '\x2', '\x2', 'M', '\xF0', 
		'\x3', '\x2', '\x2', '\x2', 'O', '\xF6', '\x3', '\x2', '\x2', '\x2', 'Q', 
		'\xFF', '\x3', '\x2', '\x2', '\x2', 'S', '\x10D', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '.', '\x2', '\x2', 'V', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\a', '$', '\x2', '\x2', 'X', '\x6', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\a', '*', '\x2', '\x2', 'Z', '\b', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', '+', '\x2', '\x2', '\\', '\n', '\x3', '\x2', '\x2', 
		'\x2', ']', '^', '\a', '\x30', '\x2', '\x2', '^', '\f', '\x3', '\x2', 
		'\x2', '\x2', '_', '`', '\a', ']', '\x2', '\x2', '`', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '\x62', '\a', '_', '\x2', '\x2', '\x62', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', '/', '\x2', '\x2', '\x64', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', '%', '\x2', 
		'\x2', '\x66', '\x14', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\x30', 
		'\x2', '\x2', 'h', 'i', '\a', '\x724A', '\x2', '\x2', 'i', 'j', '\a', 
		'\x672E', '\x2', '\x2', 'j', '\x16', '\x3', '\x2', '\x2', '\x2', 'k', 
		'l', '\a', '\x30', '\x2', '\x2', 'l', 'm', '\a', '\x6531', '\x2', '\x2', 
		'm', 'n', '\a', '\x6303', '\x2', '\x2', 'n', 'o', '\a', '\x5E95', '\x2', 
		'\x2', 'o', '\x18', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '\x30', 
		'\x2', '\x2', 'q', 'r', '\a', '\x7A0D', '\x2', '\x2', 'r', 's', '\a', 
		'\x5E91', '\x2', '\x2', 's', 't', '\a', '\x96C8', '\x2', '\x2', 't', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '\x30', '\x2', '\x2', 'v', 
		'w', '\a', '\x7A0D', '\x2', '\x2', 'w', 'x', '\a', '\x5E91', '\x2', '\x2', 
		'x', 'y', '\a', '\x96C8', '\x2', '\x2', 'y', 'z', '\a', '\x53DA', '\x2', 
		'\x2', 'z', '{', '\a', '\x91D1', '\x2', '\x2', '{', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '|', '}', '\a', '\x30', '\x2', '\x2', '}', '~', '\a', '\x5C42', 
		'\x2', '\x2', '~', '\x7F', '\a', '\x90EA', '\x2', '\x2', '\x7F', '\x80', 
		'\a', '\x53DA', '\x2', '\x2', '\x80', '\x81', '\a', '\x91D1', '\x2', '\x2', 
		'\x81', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '\x30', 
		'\x2', '\x2', '\x83', '\x84', '\a', '\x53C4', '\x2', '\x2', '\x84', '\x85', 
		'\a', '\x6572', '\x2', '\x2', '\x85', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x87', '\a', '\x30', '\x2', '\x2', '\x87', '\x88', '\a', '\x5B52', 
		'\x2', '\x2', '\x88', '\x89', '\a', '\x7A0D', '\x2', '\x2', '\x89', '\x8A', 
		'\a', '\x5E91', '\x2', '\x2', '\x8A', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\x8C', '\a', '\x30', '\x2', '\x2', '\x8C', '\x8D', '\a', '\x5984', 
		'\x2', '\x2', '\x8D', '\x8E', '\a', '\x679E', '\x2', '\x2', '\x8E', '\x8F', 
		'\a', '\x7721', '\x2', '\x2', '\x8F', '$', '\x3', '\x2', '\x2', '\x2', 
		'\x90', '\x91', '\a', '\x30', '\x2', '\x2', '\x91', '\x92', '\a', '\x5984', 
		'\x2', '\x2', '\x92', '\x93', '\a', '\x679E', '\x2', '\x2', '\x93', '\x94', 
		'\a', '\x7721', '\x2', '\x2', '\x94', '\x95', '\a', '\x7ED5', '\x2', '\x2', 
		'\x95', '\x96', '\a', '\x6761', '\x2', '\x2', '\x96', '&', '\x3', '\x2', 
		'\x2', '\x2', '\x97', '\x98', '\a', '\x30', '\x2', '\x2', '\x98', '\x99', 
		'\a', '\x5984', '\x2', '\x2', '\x99', '\x9A', '\a', '\x679E', '\x2', '\x2', 
		'\x9A', '(', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x30', 
		'\x2', '\x2', '\x9C', '\x9D', '\a', '\x5428', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', '\x521B', '\x2', '\x2', '\x9E', '*', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '\xA0', '\a', '\x30', '\x2', '\x2', '\xA0', '\xA1', '\a', '\x5984', 
		'\x2', '\x2', '\xA1', '\xA2', '\a', '\x679E', '\x2', '\x2', '\xA2', '\xA3', 
		'\a', '\x7ED5', '\x2', '\x2', '\xA3', '\xA4', '\a', '\x6761', '\x2', '\x2', 
		'\xA4', ',', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x30', 
		'\x2', '\x2', '\xA6', '\xA7', '\a', '\x5226', '\x2', '\x2', '\xA7', '\xA8', 
		'\a', '\x65AF', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x5FAC', '\x2', '\x2', 
		'\xA9', '\xAA', '\a', '\x73B1', '\x2', '\x2', '\xAA', '\xAB', '\a', '\x9998', 
		'\x2', '\x2', '\xAB', '.', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', 
		'\a', '\x30', '\x2', '\x2', '\xAD', '\xAE', '\a', '\x5226', '\x2', '\x2', 
		'\xAE', '\xAF', '\a', '\x65AF', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x5FAC', 
		'\x2', '\x2', '\xB0', '\xB1', '\a', '\x73B1', '\x2', '\x2', '\xB1', '\xB2', 
		'\a', '\x5C40', '\x2', '\x2', '\xB2', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\xB3', '\xB4', '\a', '\x30', '\x2', '\x2', '\xB4', '\xB5', '\a', '\x8BA3', 
		'\x2', '\x2', '\xB5', '\xB6', '\a', '\x6B23', '\x2', '\x2', '\xB6', '\xB7', 
		'\a', '\x5FAC', '\x2', '\x2', '\xB7', '\xB8', '\a', '\x73B1', '\x2', '\x2', 
		'\xB8', '\xB9', '\a', '\x9998', '\x2', '\x2', '\xB9', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\xBA', '\xBB', '\a', '\x30', '\x2', '\x2', '\xBB', '\xBC', 
		'\a', '\x8BA3', '\x2', '\x2', '\xBC', '\xBD', '\a', '\x6B23', '\x2', '\x2', 
		'\xBD', '\xBE', '\a', '\x5FAC', '\x2', '\x2', '\xBE', '\xBF', '\a', '\x73B1', 
		'\x2', '\x2', '\xBF', '\xC0', '\a', '\x5C40', '\x2', '\x2', '\xC0', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', '\xFF0D', '\x2', '\x2', 
		'\xC2', '\x36', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\a', '\xFF0F', 
		'\x2', '\x2', '\xC4', '\x38', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', 
		'\a', '\xD9', '\x2', '\x2', '\xC6', ':', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', '\xF9', '\x2', '\x2', '\xC8', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\a', '\xFF1F', '\x2', '\x2', '\xCA', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', '\x2262', '\x2', '\x2', '\xCC', 
		'@', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\a', '\x6218', '\x2', 
		'\x2', '\xCE', '\x42', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD1', '\x4', 
		'\x32', ';', '\x2', '\xD0', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xD2', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD3', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD6', '\x5', '\x43', '\"', '\x2', '\xD5', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\x3', '\x2', '\x2', 
		'\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\a', 
		'\x30', '\x2', '\x2', '\xD8', '\xDF', '\x5', '\x43', '\"', '\x2', '\xD9', 
		'\xDA', '\x5', '\x43', '\"', '\x2', '\xDA', '\xDC', '\a', '\x30', '\x2', 
		'\x2', '\xDB', '\xDD', '\x5', '\x43', '\"', '\x2', '\xDC', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDF', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDF', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\xE0', '\xE1', '\t', '\x2', '\x2', '\x2', '\xE1', 
		'H', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE5', '\t', '\x3', '\x2', '\x2', 
		'\xE3', '\xE5', '\x5', 'G', '$', '\x2', '\xE4', '\xE2', '\x3', '\x2', 
		'\x2', '\x2', '\xE4', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', 
		'\x3', '\x2', '\x2', '\x2', '\xE6', '\xE4', '\x3', '\x2', '\x2', '\x2', 
		'\xE6', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE7', 'J', '\x3', '\x2', 
		'\x2', '\x2', '\xE8', '\xEA', '\t', '\x4', '\x2', '\x2', '\xE9', '\xE8', 
		'\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEC', '\x3', '\x2', 
		'\x2', '\x2', '\xEC', '\xED', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEE', 
		'\b', '&', '\x2', '\x2', '\xEE', 'L', '\x3', '\x2', '\x2', '\x2', '\xEF', 
		'\xF1', '\a', '\xF', '\x2', '\x2', '\xF0', '\xEF', '\x3', '\x2', '\x2', 
		'\x2', '\xF0', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\xF2', '\xF3', '\a', '\f', '\x2', '\x2', '\xF3', 
		'\xF4', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\b', '\'', '\x2', 
		'\x2', '\xF5', 'N', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xFA', '\a', 
		'\x201E', '\x2', '\x2', '\xF7', '\xF9', '\v', '\x2', '\x2', '\x2', '\xF8', 
		'\xF7', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xFC', '\x3', '\x2', '\x2', 
		'\x2', '\xFA', '\xFB', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xF8', '\x3', 
		'\x2', '\x2', '\x2', '\xFB', '\xFD', '\x3', '\x2', '\x2', '\x2', '\xFC', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', '\xFD', '\xFE', '\a', '\x201F', '\x2', 
		'\x2', '\xFE', 'P', '\x3', '\x2', '\x2', '\x2', '\xFF', '\x103', '\a', 
		')', '\x2', '\x2', '\x100', '\x102', '\v', '\x2', '\x2', '\x2', '\x101', 
		'\x100', '\x3', '\x2', '\x2', '\x2', '\x102', '\x105', '\x3', '\x2', '\x2', 
		'\x2', '\x103', '\x104', '\x3', '\x2', '\x2', '\x2', '\x103', '\x101', 
		'\x3', '\x2', '\x2', '\x2', '\x104', '\x107', '\x3', '\x2', '\x2', '\x2', 
		'\x105', '\x103', '\x3', '\x2', '\x2', '\x2', '\x106', '\x108', '\a', 
		'\xF', '\x2', '\x2', '\x107', '\x106', '\x3', '\x2', '\x2', '\x2', '\x107', 
		'\x108', '\x3', '\x2', '\x2', '\x2', '\x108', '\x109', '\x3', '\x2', '\x2', 
		'\x2', '\x109', '\x10A', '\a', '\f', '\x2', '\x2', '\x10A', '\x10B', '\x3', 
		'\x2', '\x2', '\x2', '\x10B', '\x10C', '\b', ')', '\x2', '\x2', '\x10C', 
		'R', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x10E', '\v', '\x2', '\x2', 
		'\x2', '\x10E', 'T', '\x3', '\x2', '\x2', '\x2', '\xE', '\x2', '\xD2', 
		'\xD5', '\xDC', '\xDE', '\xE4', '\xE6', '\xEB', '\xF0', '\xFA', '\x103', 
		'\x107', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
