//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Project/OpenELanguage/Compiler\openeLang.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="openeLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IopeneLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.opene_src"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpene_src([NotNull] openeLangParser.Opene_srcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.src_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_content([NotNull] openeLangParser.Src_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.program_set_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram_set_file([NotNull] openeLangParser.Program_set_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.data_structure_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_structure_file([NotNull] openeLangParser.Data_structure_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.global_variable_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_variable_file([NotNull] openeLangParser.Global_variable_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.dll_define_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDll_define_file([NotNull] openeLangParser.Dll_define_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.dll_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDll_command([NotNull] openeLangParser.Dll_commandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.global_variable_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_variable_list([NotNull] openeLangParser.Global_variable_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.global_variable_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_variable_item([NotNull] openeLangParser.Global_variable_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.edition_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdition_spec([NotNull] openeLangParser.Edition_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.struct_declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declare([NotNull] openeLangParser.Struct_declareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.table_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_comment([NotNull] openeLangParser.Table_commentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.member_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_item([NotNull] openeLangParser.Member_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.library_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_spec([NotNull] openeLangParser.Library_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.prog_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set([NotNull] openeLangParser.Prog_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.prog_set_variable_decl_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set_variable_decl_opt([NotNull] openeLangParser.Prog_set_variable_decl_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.prog_set_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_set_variable_decl([NotNull] openeLangParser.Prog_set_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_decl([NotNull] openeLangParser.Variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.sub_program_opt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_program_opt([NotNull] openeLangParser.Sub_program_optContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.sub_program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_program([NotNull] openeLangParser.Sub_programContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.parameter_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_decl([NotNull] openeLangParser.Parameter_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.local_variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocal_variable_decl([NotNull] openeLangParser.Local_variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] openeLangParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConditionStatement</c>
	/// labeled alternative in <see cref="openeLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionStatement([NotNull] openeLangParser.ConditionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignStatement</c>
	/// labeled alternative in <see cref="openeLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStatement([NotNull] openeLangParser.AssignStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="openeLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] openeLangParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LoopStatement</c>
	/// labeled alternative in <see cref="openeLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopStatement([NotNull] openeLangParser.LoopStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchStatement</c>
	/// labeled alternative in <see cref="openeLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] openeLangParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] openeLangParser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="openeLangParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] openeLangParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RangeFor</c>
	/// labeled alternative in <see cref="openeLangParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeFor([NotNull] openeLangParser.RangeForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>For</c>
	/// labeled alternative in <see cref="openeLangParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] openeLangParser.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoWhile</c>
	/// labeled alternative in <see cref="openeLangParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhile([NotNull] openeLangParser.DoWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="openeLangParser.condition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] openeLangParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfTrueStmt</c>
	/// labeled alternative in <see cref="openeLangParser.condition_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfTrueStmt([NotNull] openeLangParser.IfTrueStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.hierarchy_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierarchy_identifier([NotNull] openeLangParser.Hierarchy_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCall</c>
	/// labeled alternative in <see cref="openeLangParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] openeLangParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="openeLangParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] openeLangParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayIndex</c>
	/// labeled alternative in <see cref="openeLangParser.name_component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayIndex([NotNull] openeLangParser.ArrayIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bracket</c>
	/// labeled alternative in <see cref="openeLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket([NotNull] openeLangParser.BracketContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OptElement</c>
	/// labeled alternative in <see cref="openeLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptElement([NotNull] openeLangParser.OptElementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryExpr</c>
	/// labeled alternative in <see cref="openeLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExpr([NotNull] openeLangParser.BinaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="openeLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] openeLangParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.data_set_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_set_value([NotNull] openeLangParser.Data_set_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.datetime_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_value([NotNull] openeLangParser.Datetime_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DatetimePureNumber</c>
	/// labeled alternative in <see cref="openeLangParser.datetime_value_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetimePureNumber([NotNull] openeLangParser.DatetimePureNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DatetimeSeparateByChinese</c>
	/// labeled alternative in <see cref="openeLangParser.datetime_value_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetimeSeparateByChinese([NotNull] openeLangParser.DatetimeSeparateByChineseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DatetimeSeparateBySlash</c>
	/// labeled alternative in <see cref="openeLangParser.datetime_value_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetimeSeparateBySlash([NotNull] openeLangParser.DatetimeSeparateBySlashContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DatetimeSeparateBySlashColon</c>
	/// labeled alternative in <see cref="openeLangParser.datetime_value_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetimeSeparateBySlashColon([NotNull] openeLangParser.DatetimeSeparateBySlashColonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DatetimeSeparateByBar</c>
	/// labeled alternative in <see cref="openeLangParser.datetime_value_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetimeSeparateByBar([NotNull] openeLangParser.DatetimeSeparateByBarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DatetimeSeparateByBarColon</c>
	/// labeled alternative in <see cref="openeLangParser.datetime_value_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetimeSeparateByBarColon([NotNull] openeLangParser.DatetimeSeparateByBarColonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.macro_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_value([NotNull] openeLangParser.Macro_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.func_ptr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_ptr([NotNull] openeLangParser.Func_ptrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.bool_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_value([NotNull] openeLangParser.Bool_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="openeLangParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] openeLangParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Float</c>
	/// labeled alternative in <see cref="openeLangParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] openeLangParser.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="openeLangParser.string_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_value([NotNull] openeLangParser.String_valueContext context);
}
