
#MACRO(REF_LLVM_PKG)

    FIND_PACKAGE(LLVM 9 REQUIRED QUIET CONFIG)
    MESSAGE(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
    MESSAGE(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
    SET(REAL_LLVM_INCLUDE_DIRS )
    IF (UNIX)
        FOREACH(LLVM_INCLUDE_DIR ${LLVM_INCLUDE_DIRS})
            SET(LLVM_INC_DIR "${LLVM_INCLUDE_DIR}/llvm")
            IF (IS_SYMLINK ${LLVM_INC_DIR})
                FILE(READ_SYMLINK "${LLVM_INC_DIR}" FOLLOW_SYMLINK)
                get_filename_component(INC_ABSOLUTE ${LLVM_INCLUDE_DIR}/${FOLLOW_SYMLINK}/../ ABSOLUTE)
                LIST(APPEND REAL_LLVM_INCLUDE_DIRS ${INC_ABSOLUTE})
            ENDIF()
        ENDFOREACH()
    ENDIF()
    MESSAGE(STATUS "${REAL_LLVM_INCLUDE_DIRS};${LLVM_INCLUDE_DIRS}")

    INCLUDE_DIRECTORIES(${REAL_LLVM_INCLUDE_DIRS})
    INCLUDE_DIRECTORIES(${LLVM_INCLUDE_DIRS})
    ADD_DEFINITIONS(${LLVM_DEFINITIONS})

#ENDMACRO()
